sandbox = {
    {
        type = "prop",
        file = "floor",
        scale = 150,
        x = 0,
        y = 0,
        collides = false,
		rot = 0,
    },
    {
        type = "prop",
        file = "wall1",
        scale = 38,
        x = 0,
        y = 300,
        collides = true,
		rot = 0,
    },
    {
        type = "prop",
        file = "wall1",
        scale = 38,
        x = 0,
       y = -300,
        collides = true,
		rot = 0,
    },
    {
        type = "prop",
        file = "wall2",
        scale = 38,
        x = 300,
        y = 0,
        collides = true,
		rot = 0,
    },
    {
        type = "prop",
        file = "wall2",
        scale = 38,
        x = -300,
        y = 0,
        collides = true,
		rot = 0,
    },
	{
        type = "entity",
        file = "player",
        x = 0,
        y = 0,
    },
    {
        type = "entity",
        file = "sandbox",
        x = 0,
        y = 0,
    }
}
